### ISSUE TITLE
exception on empty files

### ISSUE THREAD

**Issue by pavelstudeny** [robertknight/xar-js#2]
when a file size in the input directory is 0, xar-js says

var r = binding.read(fd, buffer, offset, length, position);
                  ^
Error: Offset is out of bounds
    at Error (native)
    at Object.fs.readSync (fs.js:554:19)
    at FileReader.read (/Users/studeny/src/robertknight/xar-js/build/src/io.js:18:12)
    at /Users/studeny/src/robertknight/xar-js/build/src/lib.js:287:41
    at Array.forEach (native)
    at XarArchive.generate (/Users/studeny/src/robertknight/xar-js/build/src/lib.js:282:18)
    at generateArchive (/Users/studeny/src/robertknight/xar-js/build/src/cli.js:23:13)
    at Command.<anonymous> (/Users/studeny/src/robertknight/xar-js/build/src/cli.js:35:5)
    at Command.listener (/Users/studeny/src/robertknight/xar-js/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:110:17)

**Comment by robertknight** [comment]
Related to https://github.com/nodejs/node-v0.x-archive/issues/5685
